name: Bug report
description: 提交一个 Bug
body:
  - type: markdown
    attributes:
      value: |
        请按照此模版填写 Bug 界面的快照
  - type: textarea
    id: feature-description
    attributes:
      label: 请输入 误触/不执行规则 的界面的快照, 也可在后面补充其它信息
      description: |
        按照此教程 [CONTRIBUTING.md](https://github.com/gkd-kit/subscription/blob/main/CONTRIBUTING.md) 或者下面的截图示例 来给界面打快照, 并粘贴到下面的输入框\
        ![img](https://user-images.githubusercontent.com/45487685/270372181-9e05a475-6664-4e1b-adc7-1e3973fff01f.png)\
        此外需提供 [主页-点击记录] 的截图
    validations:
      required: true
